### ISSUE TITLE
xcode error

### ISSUE THREAD

**Issue by devdudeio** [spencercarli/meteor-todos-react-native-2#14]
when I try to run this with Xcode I got this error

```
Error: Cannot find module './modules/es5'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/dude/Desktop/meteor-todos-react-native/ReactNativeTodos/node_modules/react-native/node_modules/babel-core/node_modules/core-js/shim.js:1:63)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
Command /bin/sh failed with exit code 1
```

**Comment by spencercarli** [comment]
Hey, I just updated the RN app to use the latest version and fixed a few issues I was running into. Hoping this was fixed in there as well. Could you try cloning the repo again and try running the new copy? If it doesn't work out please reopen this issue. Thanks!

**Comment by devdudeio** [comment]
now I have this error when I do `npm install && npm run ios`

```
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! ReactNativeTodos@0.0.1 start: `node_modules/react-native/packager/packager.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ReactNativeTodos@0.0.1 start script 'node_modules/react-native/packager/packager.sh'.
npm ERR! This is most likely a problem with the ReactNativeTodos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node_modules/react-native/packager/packager.sh
npm ERR! You can get their info via:
npm ERR!     npm owner ls ReactNativeTodos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/robertlech/Downloads/meteor-todos-react-native-master/ReactNativeTodos/npm-debug.log

npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "ios"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code ELIFECYCLE
npm ERR! ReactNativeTodos@0.0.1 ios: `open ios/ReactNativeTodos.xcodeproj && REACT_EDITOR=atom npm start`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ReactNativeTodos@0.0.1 ios script 'open ios/ReactNativeTodos.xcodeproj && REACT_EDITOR=atom npm start'.
npm ERR! This is most likely a problem with the ReactNativeTodos package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     open ios/ReactNativeTodos.xcodeproj && REACT_EDITOR=atom npm start
npm ERR! You can get their info via:
npm ERR!     npm owner ls ReactNativeTodos
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/robertlech/Downloads/meteor-todos-react-native-master/ReactNativeTodos/npm-debug.log
Roberts-iMac:ReactNativeTodos robertlech$ 

```

<img src="https://cloud.githubusercontent.com/assets/3764301/12890973/2ff2d59e-ce86-11e5-9f56-83a2b4116ab3.jpg" width="350">

when I manually set the port to 3000 I got this error

<img src="https://cloud.githubusercontent.com/assets/3764301/12891086/b2214af0-ce86-11e5-9f99-2bfd0c5abb9b.jpg" width="350">

in all cases I still get this error message in a new terminal window while build&run this in Xcode:

```
Error: Cannot find module './modules/es5'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/Users/robertlech/Downloads/meteor-todos-react-native-master/ReactNativeTodos/node_modules/react-native/node_modules/babel-polyfill/node_modules/core-js/shim.js:1:63)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
~
Process terminated. Press <enter> to close the window
```

btw I cant reopen issues in this repo

**Comment by spencercarli** [comment]
@rlech thanks for the details. Could you try running the app with node v5.x and npm v3.x? I've only tested the app w/ those versions.

**Comment by spencercarli** [comment]
Going to close this for now. If you or any one else run into this issue please let me know.

This looks like it was related to babel - hoping it was fixed in more recent releases (there were some issues a few releases ago).

**Comment by adeshpande3** [comment]
I am also getting the error (not on this particular project, but on any react-native example) in the orginal post . I'm not running on XCode, though. I am doing react-native run-android
